#!/usr/bin/env python

'''
zbdump - a tcpdump-like tool for ZigBee/IEEE 802.15.4 networks

Compatible with Wireshark 1.1.2 and later (jwright@willhackforsushi.com)
The -p flag adds CACE PPI headers to the PCAP (ryan@rmspeers.com)

Contribution by Don C. Weber (@cutaway), InGuardians, Inc. - packet display
'''

import sys
import signal
import argparse

from killerbee import *

def interrupt(signum, frame):
    global packetcount
    global kb
    global pd, dt
    kb.sniffer_off()
    kb.close()
    if pd:
        pd.close()
    if dt:
        dt.close()
    print("{0} packets captured".format(packetcount))
    sys.exit(0)

# PcapDumper, only used if -w is specified
pd = None
# DainTreeDumper, only used if -W is specified
dt = None

# Global
packetcount = 0

# Command-line arguments
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('-i', '--iface', '--dev', action='store', dest='devstring')
#parser.add_argument('-g', '--gps', '--ignore', action='append', dest='ignore')
parser.add_argument('-w', '--pcapfile', action='store')
parser.add_argument('-W', '--dsnafile', action='store')
parser.add_argument('-p', '--ppi', action='store_true')
parser.add_argument('-c', '-f', '--channel', action='store', type=int, default=None)
parser.add_argument('-n', '--count', action='store', type=int, default=-1)
parser.add_argument('-D', action='store_true', dest='showdev')
parser.add_argument('-q', '--quiet', action='store_false', default=True, help='Disable showing packets.')
parser.add_argument('-s', '--scapy_com', action='store_true', default=False, help='Use scapy-com package to display packet. Default: killerbee parsing.')
args = parser.parse_args()

SCAPY_COM = False
# Don't import scapy-com unless necessary
if args.scapy_com and args.quiet:
    try:
        from scapy.layers.dot15d4 import *
        SCAPY_COM = True
    except:
        pass

if args.showdev:
    show_dev()
    sys.exit(0)

if args.channel == None:
    print >>sys.stderr, "ERROR: Must specify a channel."
    sys.exit(1)

if args.pcapfile is None and args.dsnafile is None:
    print >>sys.stderr, "ERROR: Must specify a savefile with -w (libpcap) or -W (Daintree SNA)"
    sys.exit(1)
if args.pcapfile is not None:
    pd = PcapDumper(DLT_IEEE802_15_4, args.pcapfile, ppi=args.ppi)
if args.dsnafile is not None:
    dt = DainTreeDumper(args.dsnafile)

kb = KillerBee(device=args.devstring)
signal.signal(signal.SIGINT, interrupt)
if not kb.is_valid_channel(args.channel):
    print >>sys.stderr, "ERROR: Must specify a valid IEEE 802.15.4 channel for the selected device."
    kb.close()
    sys.exit(1)
kb.set_channel(args.channel)
kb.sniffer_on()

print("zbdump: listening on \'{0}\', link-type DLT_IEEE802_15_4, capture size 127 bytes".format(kb.get_dev_info()[0]))

# Parse packet to show we are receiving data
#if (args.scapy_com) and not SCAPY_COM:
if (args.quiet) and (args.scapy_com) and not SCAPY_COM:
    print
    print "WARNING: scapy-com package is not available. Continuing without it."
    print

if (args.quiet) and not (args.scapy_com):
    d154 = Dot154PacketParser()
    print
    print 'Packet: FCF | Seq# | DPAN | DA | SPAN | SA | [Beacon Data] | PHY Payload'
    print 'Beacon: Superframe Spec | GTS Fields | Pending Addr Counts | Proto ID | Stack Profile/Profile Version | Device Capabilities | Ext PAN ID | TX Offset | Update ID'
    print

rf_freq_mhz = (args.channel - 10) * 5 + 2400
while args.count != packetcount:
    packet = kb.pnext()
    # packet[1] is True if CRC is correct, check removed to have promiscous capture regardless of CRC
    if packet != None: # and packet[1]:
        
        # Parse packet to show we are receiving data
        if (args.quiet):
            if SCAPY_COM and args.scapy_com:
                p = Dot15d4(packet[0])
                print
                print p.mysummary
            else:
                pktdecode = d154.pktchop(packet[0])
                fcf = struct.unpack("<H", pktdecode[0])[0]
                if (fcf & DOT154_FCF_TYPE_MASK) == DOT154_FCF_TYPE_BEACON:
                    print "Beacon:",pktdecode
                else:
                    print "Packet:",pktdecode
                

        packetcount+=1
        if pd:
            pd.pcap_dump(packet['bytes'], ant_dbm=packet['dbm'], freq_mhz=rf_freq_mhz)
        if dt:
            dt.pwrite(packet['bytes'])

kb.sniffer_off()
kb.close()
if pd:
    pd.close()
if dt:
    dt.close()

print("{0} packets captured".format(packetcount))

